services:
  backend:
    build:
      context: .
    container_name: saas-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db

  frontdend:
    build:
      context: ../frontend-nextjs/
    container_name: saas-frontend
    env_file:
      - ../frontend-nextjs/.env
    ports:
      - "3000:3000"
    volumes:
      - ../frontend-nextjs:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: saas-db
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
