# Generated by Django 5.2 on 2025-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'plus', 'premium'], 'content_type__app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'permissions': [('basic', 'Basic Perm'), ('plus', 'Plus Perm'), ('premium', 'Premium Perm')],
            },
        ),
    ]
