# Generated by Django 5.2 on 2025-04-29 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='Subscription',
            new_name='subscription',
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=50, null=True)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=8)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
