# Generated by Django 5.2 on 2025-04-29 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionplanprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'featured', '-updated_at'], 'permissions': [('basic', 'Basic Perm'), ('plus', 'Plus Perm'), ('premium', 'Premium Perm')]},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 29, 11, 36, 19, 173765, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
