# Generated by Django 5.2 on 2025-05-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order'], 'permissions': [('basic', 'Basic Perm'), ('plus', 'Plus Perm'), ('premium', 'Premium Perm')]},
        ),
    ]
