# Generated by Django 5.2 on 2025-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_usersubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
