# Generated by Django 5.2 on 2025-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
